### ISSUE TITLE
holding flowtools oddly

### ISSUE THREAD

**Issue by SpiderOverlord** [yrsegal/PSIonic-Upgrades#10]
for some reason I can't seem to hold the flowtools correctly in game

**Comment by yrsegal** [comment]
This isn't enough information for me to fix or even diagnose the problem. Please send screenshots, and other relevant information.

**Comment by xt449** [comment]
First-person item render appears to be below the player and rotated 90 degrees
![image](https://cloud.githubusercontent.com/assets/3751431/19493722/d9598238-9549-11e6-9b0b-b11a8930ecb6.png)
![image](https://cloud.githubusercontent.com/assets/3751431/19493745/f6cf261a-9549-11e6-96ad-314cd1d73a97.png)
Images from client with Optifine 1.10.2-1 HD U D1

Renders the same way regardless of Custom Item Models and Custom Entity Models setting.

**Comment by yrsegal** [comment]
Can you reproduce this without optifine?

**Comment by yrsegal** [comment]
Actually, this appears to be the same issue as #9. Folding them into one.
