### ISSUE TITLE
[1.10.2] Crash when loading Mod with new Psi

### ISSUE THREAD

**Issue by Morpheus1101** [yrsegal/PSIonic-Upgrades#11]
Crash report @ http://pastebin.com/CXbD0shT

**Comment by kreezxil** [comment]
Confirmed

Issue:  psionic upgrades r1.13 crashes dedicated Forge 1.10.2 build 2076 on startup

crash report:
https://gist.github.com/1abc15ac6a92e34aa95310eafe272a3e

fml server latest:
https://gist.github.com/cf4e5c3b1bc50bf842d8847dc0c97565

**Comment by enkryptor** [comment]
I can confirm the crash. It occurs every time on loading, but only when Botania is present in the modpack.

http://pastebin.com/f1sKCTrF

**Comment by Hypsellis** [comment]
I hope this bug will be corrected soon. ;)

**Comment by yrsegal** [comment]
31d4b4f8c55f3995b877eb3819c51ce8d0d290a8
