### ISSUE TITLE
Wrong recipe displayed for magazine in JEI

### ISSUE THREAD

**Issue by Madcliff** [yrsegal/PSIonic-Upgrades#12]
I cannot seem to find a working recipe for magazines in JEI, it suggests psimetal and psi drives.

**Comment by yrsegal** [comment]
That's correct, isn't it?

**Comment by Madcliff** [comment]
But how then do you craft it? Trying to craft it in the crafting table fails, as there does not seem to be a way to pull it out, and how do you get different magazine sizes?

**Comment by yrsegal** [comment]
you get different magazine sizes based on the socket you put in. You are using a socket in the recipe, right?

**Comment by Madcliff** [comment]
The recipe in NEI is for two spell drives and three psi metal. There is no identification for where to pull a socket.

**Comment by yrsegal** [comment]
That's not what shows up in JEI for me. Please screenshot.

**Comment by Madcliff** [comment]
![image](https://cloud.githubusercontent.com/assets/11144102/18630421/20d9385e-7e9f-11e6-9cbd-6fdffe8dbb3b.png)

**Comment by yrsegal** [comment]
That's... strange. I'll investigate it... for now put a socket in between the drives.

**Comment by Madcliff** [comment]
Ah ok thanks :D

**Comment by yrsegal** [comment]
Fixed in latest release. I'm not quite sure what it was, but it's fixed.
