### ISSUE TITLE
PSIonic Upgrades' C.A.D.s aren't registering as C.A.D.s

### ISSUE THREAD

**Issue by GazbonicAcid** [yrsegal/PSIonic-Upgrades#6]
PSIonic Upgrades' "In-line Caster" and "Flash Ring" aren't registering as C.A.D.
You HAVE TO have an assemble C.A.D. from Psi in your inventory to be able to use them.
I seriously doubt this is intentional as it makes it pointless and a waste of Psi Metal/Gem to make the In-line Caster.
Why would you want to waste those Psi Metal ingots and those Psi Gems when the user is going to have to carry an "official" C.A.D. anyway to be able to use it?
Edit: Please note however they PSIonic Upgrades' C.A.D.s work completely if you DO have an assembled "official" C.A.D.

**Comment by yrsegal** [comment]
Because the flash ring is for on-the-go programming, and the Inline Caster for having quick access to a spell. Neither of them ARE CADs. Works as Intended.

**Comment by GazbonicAcid** [comment]
I understand it being intended for the flash ring, but not the In-line caster.
Only ways that needing one makes sense that I can think of is
1. if you could load a spell directly on-to it without a spell bullet
2. or you could load bullets the same way as your magazines without needing a cad assembler

Personally I think the second one is better.

**Comment by majix560** [comment]
@yrsegal don't forget to read my reply please

**Comment by yrsegal** [comment]
It's meant for holding a single spell you use a lot. None of those things would make sense with it at all.
