### ISSUE TITLE
Gauss Rifle DC's players when hit

### ISSUE THREAD

**Issue by CaptainPepperjack** [yrsegal/PSIonic-Upgrades#7]
Playing on the All The Mods modpack on the testing server. Whenever a player is shot with a Gauss Rifle they disconnect from the server instantly.

**Comment by yrsegal** [comment]
Log of that player, please?

**Comment by CaptainPepperjack** [comment]
Took a minute to get it to reproduce. Here's one of the players logs http://pastebin.com/JeB8ukqc

**Comment by yrsegal** [comment]
I can't see what's happening from that log; i'll test it and see what I can find. Is any error being thrown in the server log, or is the player just DCing?

**Comment by yrsegal** [comment]
@CaptainPepperjack any news on the logs?

**Comment by SweetSugarSugar** [comment]
Having this same issue as well.

**Comment by yrsegal** [comment]
Yep, I'm still working on tracking down the exact cause

**Comment by hexicles** [comment]
Not sure if it's just the projectile but after firing off into the distance and letting the projectile hit the chunk boundary, loading the chunk again causes a fatal error leading to d/c
here's what the log prints when attempting to rejoin the server after disconnecting.

https://gist.github.com/TehColt/08357da990790069f288b2986e57d852

**Comment by yrsegal** [comment]
31d4b4f8c55f3995b877eb3819c51ce8d0d290a8
